### Recuperar todas las citas
GET http://localhost:1234/dates

### Recuperar una cita por id
GET http://localhost:1234/dates/yBONanw0uXKPcisy14Dn

### Recuperar todas las citas por una fecha
GET http://localhost:1234/dates?date=2024-05-10T10:00:00.000Z

### Crear una cita con POST
POST http://localhost:1234/dates
Content-Type: application/json

{
    "date": "2024-05-10T10:00:00.000Z",
    "scheduler": "Santiago Quinteroooooo",
    "requestedService": "Consulta",
    "clientName": "John Doeeeei",
    "clientPhone": "12345678900"
  }
### Borrar una cita
DELETE http://localhost:1234/dates/E0vjxoUgZDEcJdmm2Heb

### Actualizar una cita
PATCH http://localhost:1234/dates/2b5SBnWLMd3Rja1tmZYo
Content-Type: application/json

{
  "scheduler": "yo mero",
  "clientPhone":"3222231587"
}